/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_word = 1,
  sym_title = 2,
  sym_delta_header = 3,
  anon_sym_POUND_POUND_POUNDRequirement_COLON = 4,
  aux_sym_requirement_name_token1 = 5,
  anon_sym_SHALL = 6,
  anon_sym_NOT = 7,
  anon_sym_MUST = 8,
  sym__punctuation = 9,
  anon_sym_POUND_POUND_POUND_POUNDScenario_COLON = 10,
  anon_sym_WHEN = 11,
  anon_sym_THEN = 12,
  anon_sym_AND = 13,
  sym__bold_marker = 14,
  anon_sym_STAR_STAR = 15,
  sym_document = 16,
  sym_delta_section = 17,
  sym_requirement = 18,
  sym_requirement_name = 19,
  sym_requirement_body = 20,
  sym_keyword = 21,
  sym_scenario = 22,
  sym_scenario_name = 23,
  sym_condition = 24,
  sym_assertion = 25,
  sym_continuation = 26,
  sym__bold_end = 27,
  aux_sym_document_repeat1 = 28,
  aux_sym_delta_section_repeat1 = 29,
  aux_sym_requirement_repeat1 = 30,
  aux_sym_requirement_body_repeat1 = 31,
  aux_sym_scenario_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_word] = "word",
  [sym_title] = "title",
  [sym_delta_header] = "delta_header",
  [anon_sym_POUND_POUND_POUNDRequirement_COLON] = "### Requirement:",
  [aux_sym_requirement_name_token1] = "requirement_name_token1",
  [anon_sym_SHALL] = "SHALL",
  [anon_sym_NOT] = "NOT",
  [anon_sym_MUST] = "MUST",
  [sym__punctuation] = "_punctuation",
  [anon_sym_POUND_POUND_POUND_POUNDScenario_COLON] = "#### Scenario:",
  [anon_sym_WHEN] = "condition_keyword",
  [anon_sym_THEN] = "assertion_keyword",
  [anon_sym_AND] = "continuation_keyword",
  [sym__bold_marker] = "_bold_marker",
  [anon_sym_STAR_STAR] = "**",
  [sym_document] = "document",
  [sym_delta_section] = "delta_section",
  [sym_requirement] = "requirement",
  [sym_requirement_name] = "requirement_name",
  [sym_requirement_body] = "requirement_body",
  [sym_keyword] = "keyword",
  [sym_scenario] = "scenario",
  [sym_scenario_name] = "scenario_name",
  [sym_condition] = "condition",
  [sym_assertion] = "assertion",
  [sym_continuation] = "continuation",
  [sym__bold_end] = "_bold_end",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_delta_section_repeat1] = "delta_section_repeat1",
  [aux_sym_requirement_repeat1] = "requirement_repeat1",
  [aux_sym_requirement_body_repeat1] = "requirement_body_repeat1",
  [aux_sym_scenario_repeat1] = "scenario_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_word] = sym_word,
  [sym_title] = sym_title,
  [sym_delta_header] = sym_delta_header,
  [anon_sym_POUND_POUND_POUNDRequirement_COLON] = anon_sym_POUND_POUND_POUNDRequirement_COLON,
  [aux_sym_requirement_name_token1] = aux_sym_requirement_name_token1,
  [anon_sym_SHALL] = anon_sym_SHALL,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_MUST] = anon_sym_MUST,
  [sym__punctuation] = sym__punctuation,
  [anon_sym_POUND_POUND_POUND_POUNDScenario_COLON] = anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
  [anon_sym_WHEN] = anon_sym_WHEN,
  [anon_sym_THEN] = anon_sym_THEN,
  [anon_sym_AND] = anon_sym_AND,
  [sym__bold_marker] = sym__bold_marker,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [sym_document] = sym_document,
  [sym_delta_section] = sym_delta_section,
  [sym_requirement] = sym_requirement,
  [sym_requirement_name] = sym_requirement_name,
  [sym_requirement_body] = sym_requirement_body,
  [sym_keyword] = sym_keyword,
  [sym_scenario] = sym_scenario,
  [sym_scenario_name] = sym_scenario_name,
  [sym_condition] = sym_condition,
  [sym_assertion] = sym_assertion,
  [sym_continuation] = sym_continuation,
  [sym__bold_end] = sym__bold_end,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_delta_section_repeat1] = aux_sym_delta_section_repeat1,
  [aux_sym_requirement_repeat1] = aux_sym_requirement_repeat1,
  [aux_sym_requirement_body_repeat1] = aux_sym_requirement_body_repeat1,
  [aux_sym_scenario_repeat1] = aux_sym_scenario_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_delta_header] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND_POUND_POUNDRequirement_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_requirement_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SHALL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MUST] = {
    .visible = true,
    .named = false,
  },
  [sym__punctuation] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND_POUND_POUND_POUNDScenario_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_WHEN] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_THEN] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = true,
  },
  [sym__bold_marker] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_delta_section] = {
    .visible = true,
    .named = true,
  },
  [sym_requirement] = {
    .visible = true,
    .named = true,
  },
  [sym_requirement_name] = {
    .visible = true,
    .named = true,
  },
  [sym_requirement_body] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario] = {
    .visible = true,
    .named = true,
  },
  [sym_scenario_name] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_assertion] = {
    .visible = true,
    .named = true,
  },
  [sym_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym__bold_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_delta_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_requirement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_requirement_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scenario_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(63);
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '-') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '*') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(61);
      if (lookahead == '#') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(14);
      if (lookahead == '#') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(29);
      if (lookahead == '#') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(75);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(74);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(73);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(66);
      END_STATE();
    case 14:
      if (lookahead == 'A') ADVANCE(17);
      if (lookahead == 'M') ADVANCE(28);
      if (lookahead == 'R') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'A') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'D') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == 'D') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'D') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'D') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'F') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'I') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'I') ADVANCE(21);
      END_STATE();
    case 25:
      if (lookahead == 'M') ADVANCE(27);
      if (lookahead == 'N') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == 'M') ADVANCE(21);
      END_STATE();
    case 27:
      if (lookahead == 'O') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'O') ADVANCE(16);
      END_STATE();
    case 29:
      if (lookahead == 'R') ADVANCE(35);
      END_STATE();
    case 30:
      if (lookahead == 'R') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'S') ADVANCE(34);
      END_STATE();
    case 32:
      if (lookahead == 'V') ADVANCE(21);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 45:
      if (lookahead == 'm') ADVANCE(38);
      END_STATE();
    case 46:
      if (lookahead == 'm') ADVANCE(39);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 48:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(57);
      END_STATE();
    case 50:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 51:
      if (lookahead == 'q') ADVANCE(59);
      END_STATE();
    case 52:
      if (lookahead == 'q') ADVANCE(60);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 54:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 56:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 59:
      if (lookahead == 'u') ADVANCE(42);
      END_STATE();
    case 60:
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 61:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 62:
      if (eof) ADVANCE(63);
      if (lookahead == '#') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_title);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_delta_header);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUNDRequirement_COLON);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_requirement_name_token1);
      if (lookahead == '*') ADVANCE(68);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(70);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_requirement_name_token1);
      if (lookahead == '*') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_requirement_name_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_requirement_name_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__punctuation);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#') ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_POUNDScenario_COLON);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__bold_marker);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'A') ADVANCE(1);
      if (lookahead == 'M') ADVANCE(2);
      if (lookahead == 'N') ADVANCE(3);
      if (lookahead == 'S') ADVANCE(4);
      if (lookahead == 'T') ADVANCE(5);
      if (lookahead == 'W') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'N') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'U') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'O') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'H') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'H') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'H') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'D') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'S') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'A') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(18);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 14:
      if (lookahead == 'T') ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    case 16:
      if (lookahead == 'L') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'N') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'N') ADVANCE(22);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_MUST);
      END_STATE();
    case 20:
      if (lookahead == 'L') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_THEN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_WHEN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SHALL);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 62},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 62},
  [7] = {.lex_state = 62},
  [8] = {.lex_state = 62},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 62},
  [11] = {.lex_state = 62},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
    [sym_title] = ACTIONS(1),
    [sym_delta_header] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUNDRequirement_COLON] = ACTIONS(1),
    [anon_sym_SHALL] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_MUST] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_POUNDScenario_COLON] = ACTIONS(1),
    [anon_sym_WHEN] = ACTIONS(1),
    [anon_sym_THEN] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [sym__bold_marker] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(40),
    [sym_delta_section] = STATE(24),
    [sym_requirement] = STATE(24),
    [aux_sym_document_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_title] = ACTIONS(5),
    [sym_delta_header] = ACTIONS(7),
    [anon_sym_POUND_POUND_POUNDRequirement_COLON] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      sym_word,
    ACTIONS(17), 1,
      sym__punctuation,
    ACTIONS(19), 1,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
    STATE(22), 1,
      sym_requirement_body,
    ACTIONS(15), 2,
      anon_sym_SHALL,
      anon_sym_MUST,
    STATE(6), 2,
      sym_keyword,
      aux_sym_requirement_body_repeat1,
    STATE(23), 2,
      sym_scenario,
      aux_sym_requirement_repeat1,
    ACTIONS(11), 4,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
  [31] = 6,
    ACTIONS(23), 1,
      anon_sym_WHEN,
    ACTIONS(25), 1,
      anon_sym_THEN,
    ACTIONS(27), 1,
      anon_sym_AND,
    ACTIONS(29), 1,
      sym__bold_marker,
    STATE(4), 4,
      sym_condition,
      sym_assertion,
      sym_continuation,
      aux_sym_scenario_repeat1,
    ACTIONS(21), 5,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
  [57] = 6,
    ACTIONS(23), 1,
      anon_sym_WHEN,
    ACTIONS(25), 1,
      anon_sym_THEN,
    ACTIONS(27), 1,
      anon_sym_AND,
    ACTIONS(29), 1,
      sym__bold_marker,
    STATE(5), 4,
      sym_condition,
      sym_assertion,
      sym_continuation,
      aux_sym_scenario_repeat1,
    ACTIONS(31), 5,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
  [83] = 6,
    ACTIONS(35), 1,
      anon_sym_WHEN,
    ACTIONS(38), 1,
      anon_sym_THEN,
    ACTIONS(41), 1,
      anon_sym_AND,
    ACTIONS(44), 1,
      sym__bold_marker,
    STATE(5), 4,
      sym_condition,
      sym_assertion,
      sym_continuation,
      aux_sym_scenario_repeat1,
    ACTIONS(33), 5,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
  [109] = 5,
    ACTIONS(49), 1,
      sym_word,
    ACTIONS(51), 1,
      sym__punctuation,
    ACTIONS(15), 2,
      anon_sym_SHALL,
      anon_sym_MUST,
    STATE(7), 2,
      sym_keyword,
      aux_sym_requirement_body_repeat1,
    ACTIONS(47), 5,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
  [131] = 5,
    ACTIONS(55), 1,
      sym_word,
    ACTIONS(61), 1,
      sym__punctuation,
    ACTIONS(58), 2,
      anon_sym_SHALL,
      anon_sym_MUST,
    STATE(7), 2,
      sym_keyword,
      aux_sym_requirement_body_repeat1,
    ACTIONS(53), 5,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
  [153] = 3,
    ACTIONS(68), 1,
      anon_sym_NOT,
    ACTIONS(66), 3,
      anon_sym_SHALL,
      anon_sym_MUST,
      sym_word,
    ACTIONS(64), 6,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      sym__punctuation,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
  [170] = 1,
    ACTIONS(70), 9,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
      anon_sym_WHEN,
      anon_sym_THEN,
      anon_sym_AND,
      sym__bold_marker,
  [182] = 2,
    ACTIONS(74), 3,
      anon_sym_SHALL,
      anon_sym_MUST,
      sym_word,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      sym__punctuation,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
  [196] = 2,
    ACTIONS(78), 3,
      anon_sym_SHALL,
      anon_sym_MUST,
      sym_word,
    ACTIONS(76), 6,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      sym__punctuation,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
  [210] = 1,
    ACTIONS(80), 9,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
      anon_sym_WHEN,
      anon_sym_THEN,
      anon_sym_AND,
      sym__bold_marker,
  [222] = 1,
    ACTIONS(82), 9,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
      anon_sym_WHEN,
      anon_sym_THEN,
      anon_sym_AND,
      sym__bold_marker,
  [234] = 1,
    ACTIONS(84), 9,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
      anon_sym_WHEN,
      anon_sym_THEN,
      anon_sym_AND,
      sym__bold_marker,
  [246] = 1,
    ACTIONS(86), 9,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
      anon_sym_WHEN,
      anon_sym_THEN,
      anon_sym_AND,
      sym__bold_marker,
  [258] = 1,
    ACTIONS(88), 9,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
      anon_sym_WHEN,
      anon_sym_THEN,
      anon_sym_AND,
      sym__bold_marker,
  [270] = 1,
    ACTIONS(90), 9,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
      anon_sym_WHEN,
      anon_sym_THEN,
      anon_sym_AND,
      sym__bold_marker,
  [282] = 1,
    ACTIONS(92), 9,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
      anon_sym_WHEN,
      anon_sym_THEN,
      anon_sym_AND,
      sym__bold_marker,
  [294] = 1,
    ACTIONS(94), 9,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
      anon_sym_WHEN,
      anon_sym_THEN,
      anon_sym_AND,
      sym__bold_marker,
  [306] = 1,
    ACTIONS(96), 9,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
      anon_sym_WHEN,
      anon_sym_THEN,
      anon_sym_AND,
      sym__bold_marker,
  [318] = 3,
    ACTIONS(100), 1,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
    STATE(21), 2,
      sym_scenario,
      aux_sym_requirement_repeat1,
    ACTIONS(98), 4,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
  [332] = 3,
    ACTIONS(19), 1,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
    STATE(25), 2,
      sym_scenario,
      aux_sym_requirement_repeat1,
    ACTIONS(103), 4,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
  [346] = 3,
    ACTIONS(19), 1,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
    STATE(21), 2,
      sym_scenario,
      aux_sym_requirement_repeat1,
    ACTIONS(103), 4,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
  [360] = 5,
    ACTIONS(7), 1,
      sym_delta_header,
    ACTIONS(9), 1,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      sym_title,
    STATE(26), 3,
      sym_delta_section,
      sym_requirement,
      aux_sym_document_repeat1,
  [378] = 3,
    ACTIONS(19), 1,
      anon_sym_POUND_POUND_POUND_POUNDScenario_COLON,
    STATE(21), 2,
      sym_scenario,
      aux_sym_requirement_repeat1,
    ACTIONS(109), 4,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
  [392] = 5,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 1,
      sym_title,
    ACTIONS(116), 1,
      sym_delta_header,
    ACTIONS(119), 1,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
    STATE(26), 3,
      sym_delta_section,
      sym_requirement,
      aux_sym_document_repeat1,
  [410] = 3,
    ACTIONS(9), 1,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
    STATE(28), 2,
      sym_requirement,
      aux_sym_delta_section_repeat1,
    ACTIONS(122), 3,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
  [423] = 3,
    ACTIONS(9), 1,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
    STATE(29), 2,
      sym_requirement,
      aux_sym_delta_section_repeat1,
    ACTIONS(124), 3,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
  [436] = 3,
    ACTIONS(128), 1,
      anon_sym_POUND_POUND_POUNDRequirement_COLON,
    STATE(29), 2,
      sym_requirement,
      aux_sym_delta_section_repeat1,
    ACTIONS(126), 3,
      ts_builtin_sym_end,
      sym_title,
      sym_delta_header,
  [449] = 3,
    ACTIONS(131), 1,
      aux_sym_requirement_name_token1,
    ACTIONS(133), 1,
      anon_sym_STAR_STAR,
    STATE(39), 1,
      sym__bold_end,
  [459] = 3,
    ACTIONS(135), 1,
      aux_sym_requirement_name_token1,
    ACTIONS(137), 1,
      anon_sym_STAR_STAR,
    STATE(42), 1,
      sym__bold_end,
  [469] = 3,
    ACTIONS(139), 1,
      anon_sym_WHEN,
    ACTIONS(141), 1,
      anon_sym_THEN,
    ACTIONS(143), 1,
      anon_sym_AND,
  [479] = 3,
    ACTIONS(145), 1,
      aux_sym_requirement_name_token1,
    ACTIONS(147), 1,
      anon_sym_STAR_STAR,
    STATE(41), 1,
      sym__bold_end,
  [489] = 3,
    ACTIONS(149), 1,
      aux_sym_requirement_name_token1,
    ACTIONS(151), 1,
      anon_sym_STAR_STAR,
    STATE(43), 1,
      sym__bold_end,
  [499] = 3,
    ACTIONS(153), 1,
      aux_sym_requirement_name_token1,
    ACTIONS(155), 1,
      anon_sym_STAR_STAR,
    STATE(44), 1,
      sym__bold_end,
  [509] = 3,
    ACTIONS(157), 1,
      aux_sym_requirement_name_token1,
    ACTIONS(159), 1,
      anon_sym_STAR_STAR,
    STATE(45), 1,
      sym__bold_end,
  [519] = 2,
    ACTIONS(161), 1,
      aux_sym_requirement_name_token1,
    STATE(3), 1,
      sym_scenario_name,
  [526] = 2,
    ACTIONS(163), 1,
      aux_sym_requirement_name_token1,
    STATE(2), 1,
      sym_requirement_name,
  [533] = 1,
    ACTIONS(165), 1,
      aux_sym_requirement_name_token1,
  [537] = 1,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
  [541] = 1,
    ACTIONS(169), 1,
      aux_sym_requirement_name_token1,
  [545] = 1,
    ACTIONS(171), 1,
      aux_sym_requirement_name_token1,
  [549] = 1,
    ACTIONS(173), 1,
      aux_sym_requirement_name_token1,
  [553] = 1,
    ACTIONS(175), 1,
      aux_sym_requirement_name_token1,
  [557] = 1,
    ACTIONS(177), 1,
      aux_sym_requirement_name_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 57,
  [SMALL_STATE(5)] = 83,
  [SMALL_STATE(6)] = 109,
  [SMALL_STATE(7)] = 131,
  [SMALL_STATE(8)] = 153,
  [SMALL_STATE(9)] = 170,
  [SMALL_STATE(10)] = 182,
  [SMALL_STATE(11)] = 196,
  [SMALL_STATE(12)] = 210,
  [SMALL_STATE(13)] = 222,
  [SMALL_STATE(14)] = 234,
  [SMALL_STATE(15)] = 246,
  [SMALL_STATE(16)] = 258,
  [SMALL_STATE(17)] = 270,
  [SMALL_STATE(18)] = 282,
  [SMALL_STATE(19)] = 294,
  [SMALL_STATE(20)] = 306,
  [SMALL_STATE(21)] = 318,
  [SMALL_STATE(22)] = 332,
  [SMALL_STATE(23)] = 346,
  [SMALL_STATE(24)] = 360,
  [SMALL_STATE(25)] = 378,
  [SMALL_STATE(26)] = 392,
  [SMALL_STATE(27)] = 410,
  [SMALL_STATE(28)] = 423,
  [SMALL_STATE(29)] = 436,
  [SMALL_STATE(30)] = 449,
  [SMALL_STATE(31)] = 459,
  [SMALL_STATE(32)] = 469,
  [SMALL_STATE(33)] = 479,
  [SMALL_STATE(34)] = 489,
  [SMALL_STATE(35)] = 499,
  [SMALL_STATE(36)] = 509,
  [SMALL_STATE(37)] = 519,
  [SMALL_STATE(38)] = 526,
  [SMALL_STATE(39)] = 533,
  [SMALL_STATE(40)] = 537,
  [SMALL_STATE(41)] = 541,
  [SMALL_STATE(42)] = 545,
  [SMALL_STATE(43)] = 549,
  [SMALL_STATE(44)] = 553,
  [SMALL_STATE(45)] = 557,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scenario_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scenario_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement_body, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_requirement_body_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_requirement_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_requirement_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scenario_name, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement_name, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_requirement_name, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assertion, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assertion, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 4, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assertion, 4, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_requirement_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_requirement_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requirement, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delta_section, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delta_section, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_delta_section_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_delta_section_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [167] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_openspec_spec(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_word,
    .primary_state_ids = ts_primary_state_ids,
    .name = "openspec_spec",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
